DROP TABLE GALLERY_BOARD;

CREATE TABLE GALLERY_BOARD
(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(32) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000),
	POSTDATE DATE,	-- 작성일
	LASTMODIFIED DATE,	-- 최종수정일
	IP VARCHAR2(20),		-- 작성IP
	HIT NUMBER,			-- 조회수 
	FILENAME VARCHAR2(100)			-- 이미지 파일첨부
);

DROP SEQUENCE GALLERY_BOARD_SEQ;
CREATE SEQUENCE GALLERY_BOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;


