DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(32) NOT NULL UNIQUE,
	PW VARCHAR2(64) NOT NULL,
	NAME VARCHAR2(32) NOT NULL UNIQUE,
	PHONE VARCHAR2(30) NOT NULL UNIQUE,
	EMAIL VARCHAR2(50) NOT NULL,
	ADDRESS VARCHAR2(100),
	REGDATE DATE,
	STATE NUMBER -- 회원 상태 (정상: 0, 탈퇴: -1)
);

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

SELECT * FROM MEMBER;