DROP TABLE REPLY_BOARD;

CREATE TABLE REPLY_BOARD
(
	NO NUMBER PRIMARY KEY,
	GALLERY_BOARD_REPLY_ID VARCHAR2(32),
	REPLY_CONTENT VARCHAR2(400),
	REPLY_POSTDATE DATE,
	GALLERY_BOARD_REPLY_IP VARCHAR2(20)
);

-- 외래키
ALTER TABLE REPLY_BOARD ADD CONSTRAINT REPLY_BOARD_FK FOREIGN KEY(GALLERY_BOARD_REPLY_ID) REFERENCES GALLERY_BOARD(ID);
ALTER TABLE REPLY_BOARD ADD CONSTRAINT REPLY_BOARD_FK FOREIGN KEY(GALLERY_BOARD_REPLY_IP) REFERENCES GALLERY_BOARD(IP);

DROP SEQUENCE REPLY_SEQ;
CREATE SEQUENCE REPLY_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;