DROP TABLE CONTACT;

DROP SEQUENCE CONTACT_SEQ;

CREATE TABLE CONTACT 
(
    NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(32),
    TEL VARCHAR2(20),
    ADDR VARCHAR2(50),
    EMAIL VARCHAR2(30),
    NOTE VARCHAR2(1000)
);

CREATE SEQUENCE CONTACT_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

SELECT * FROM CONTACT;