DROP TABLE BOARD;
CREATE TABLE BOARD 
(
	NO NUMBER PRIMARY KEY,
	WRITER VARCHAR2(32),
	TITLE VARCHAR2(100),
	CONTENT VARCHAR2(100),
	FILENAME VARCHAR2(300),
	POSTDATE DATE			-- * 참고로 데이트는 2개를 같이 쓰는게 좋다 (최종수정일 / 작성일)
);

DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;